# Name of workflow to be displyed on Github Console
name: Build and Test Application

# Triggers the workflow on separate events
on:
  push:
    # Trigger the worflow on push event for all branches
    branches:
      -  '**'

jobs:
  build:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Python Requirements
        run: pipenv install --ignore-pipfile

      - name: Run Tests
        run: |
          pipenv run isort .
          pipenv run black --check .
          pipenv run flake8