# Name of workflow to be displyed on Github Console
name: Demo input

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        options:
          - LOCAL
          - DEV
          - PREPROD
          - PROD
        description: Specify environment

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Print the current branch name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}

      - name: Check for branch
        if: ${{ startsWith(steps.extract_branch.outputs.branch, 'release') }}
        run: echo "release branch"

      - name: Check for branch upload
        if: ${{ startsWith(steps.extract_branch.outputs.branch, 'release') && (github.event.inputs.env == 'PROD' || github.event.inputs.env == 'PREPROD')  }}
        run: exit 1
        # run: ${{  steps.extract_branch.outputs.branch != 'release' && ( github.event.inputs.env == 'PROD' || github.event.inputs.env == 'PREPROD' ) ]]; then exit 1; else exit 0; fi


      - name: Run Tests
        run: |
          echo "all good"