name: generate version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate and append to version.txt
        run: |
          echo "$(date +%s):$(git rev-parse --short HEAD)" >> version.txt


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate new id
          file_pattern: version.txt
          push_options: --force
          branch: main
