name: CI

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: pip install pipenv
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: |
            Pipfile.lock
      - run: pipenv install --ignore-pipfile

      - name: Run Tests
        run: |
          python --version
          pipenv run python main.py

#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: Generate new id
#          file_pattern: data.json
#          push_options: --force
#          branch: update_data
#          create_branch: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: update_data
          base: master
          delete-branch: true
          title: 'Update data'
          commit-message: Update cache
          labels: |
            automated pr
          body: |
            Updating data
          add-paths: |
            data.json