name: CI

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: pip install pipenv

      - name: Install Python Requirements
        run: pipenv install --ignore-pipfile

      - name: Run Tests
        run: |
          python --version
          pipenv run python main.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate new id
          file_pattern: data.json
          push_options: --force
          branch: update_data
          create_branch: true

      - uses: actions/checkout@v2
                - name: pull-request
                uses: repo-sync/pull-request@v2
                with:
                  source_branch: "update_data"                                 # If blank, default: triggered branch
                  destination_branch: "master"                      # If blank, default: master
                  pr_title: "Update data" # Title of pull request
                  pr_body: "updating data"              # Full markdown support, requires pr_title to be set
                  pr_reviewer: "arturmkr"                         # Comma-separated list (no spaces)
                  pr_assignee: "arturmkr"                         # Comma-separated list (no spaces)
                  pr_label: "auto-pr"                               # Comma-separated list (no spaces)
