name: PR add info

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install pipenv
        run: pip install pipenv
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: |
            Pipfile.lock
      - run: pipenv install --ignore-pipfile

#      - name: Run Tests
#        run: |
#          python --version
#          pipenv run python main.py

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Print the current branch name
        shell: bash
        run: echo ${{ steps.extract_branch.outputs.branch }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.extract_branch.outputs.branch != 'master' }}
        with:
          commit_message: Some commit
          push_options: --force